### PR TITLE
Fetch and Calculate Movement Endpoints

### LINKED ISSUE #127: qol/Movement time needed
# Describe the bug or feature
When a player does a movement action he does not know how much time it will take or the path taken. This is also true for the current region card, where we need to show the current movement.

# Describe the solution and what is need to be done
Add an API route to fetch a movement, as well as fix time returned in the POST movement route

### PR DESCRIPTION
**Pull request by GroellerKarim**
Added 4 new endpoints. 

### Calculate Movement Endpoints
These two endpoints exist so that the user, before they apply the movements to their armies or characters, can see the path the movement will take as well as the duration and other information. 

1. Calculate Army Movement - GET/api/movement/calculate/army
2. Calculate Char Movement - GET/api/movement/calculate/char

### Get Movements
When calling these endpoints, the application will return the current movement and the past movements of the army or character.
If there is no active movement, then that field in the response will be null.

3. Get Army Movements - GET/api/movement/army
4. Get Char Movements - GET/api/movement/char

Closes #127

### CODE REVIEW

File: src/main/java/com/ardaslegends/presentation/api/MovementRestController.java [hunk 1]
```diff
@@ -23,13 +26,68 @@ public class MovementRestController extends AbstractRestController {
...
     public static final String PATH_MOVE_CHAR = "/move-char";
     public static final String PATH_MOVE_ARMY = "/move-army-or-company";
     public static final String PATH_CANCEL_CHAR_MOVEMENT = "/cancel-char-move";
     public static final String PATH_CANCEL_ARMY_MOVEMENT = "/cancel-army-move";
 
+    public static final String PATH_CALCULATE_ARMY_MOVEMENT = "/calculate/army";
+    public static final String PATH_CALCULATE_CHAR_MOVEMENT = "/calculate/char";
 
+    @GetMapping(PATH_GET_ARMY_MOVEMENTS)
+    public HttpEntity<CurrentAndPastMovementResponse> getArmyMovements(String armyName) {
```
Comment (Luktronic) [inline src/main/java/com/ardaslegends/presentation/api/MovementRestController.java]: I'd change the parameter name to be just `name`. Short and concise. We already know it's an army because of the path

File: src/main/java/com/ardaslegends/presentation/api/MovementRestController.java [hunk 2]
```diff
@@ -23,13 +26,68 @@ public class MovementRestController extends AbstractRestController {
...
+
+        log.debug("Building response");
+        val response = new CurrentAndPastMovementResponse(movements.getFirst().orElse(null), movements.getSecond());
+
+        log.info("Successfully handled request, getArmyMovements");
+        return ResponseEntity.ok(response);
+    }
+
+    @GetMapping(PATH_GET_CHAR_MOVEMENTS)
+    public HttpEntity<CurrentAndPastMovementResponse> getCharMovements(String charName) {
```
Comment (Luktronic) [inline src/main/java/com/ardaslegends/presentation/api/MovementRestController.java]: same thing here as above

File: src/main/java/com/ardaslegends/presentation/api/MovementRestController.java [hunk 3]
```diff
@@ -23,13 +26,68 @@ public class MovementRestController extends AbstractRestController {
...
+
+        log.debug("Building response");
+        val response = new CurrentAndPastMovementResponse(movements.getFirst().orElse(null), movements.getSecond());
+
+        log.info("Successfully handled request, getCharMovements");
+        return ResponseEntity.ok(response);
+    }
+
+    @GetMapping(PATH_CALCULATE_ARMY_MOVEMENT)
+    public HttpEntity<MovementResponse> calculateArmyMove(MoveArmyDto dto) {
```
Comment (Luktronic) [inline src/main/java/com/ardaslegends/presentation/api/MovementRestController.java:67]: Personally, I'd always add the `@RequestBody` annotation to the parameter. It might not be required but imo it's better to add it for clarification. For normal RequestParameters it's fine to leave it out since they are already parameters of the function, but for request bodies I'd always add it. Or what would you say @GroellerKarim

File: src/main/java/com/ardaslegends/presentation/api/MovementRestController.java [hunk 4]
```diff
@@ -23,13 +26,68 @@ public class MovementRestController extends AbstractRestController {
...
+        val movement = wrappedServiceExecution(dto, movementService::calculateArmyMovement);
+        log.debug("Creating MovementResponse");
+        MovementResponse response = new MovementResponse(movement);
+
+        log.info("Successfully handled request - calculated army movement!");
+        return ResponseEntity.ok(response);
+    }
+
+    @GetMapping(PATH_CALCULATE_CHAR_MOVEMENT)
+    public HttpEntity<MovementResponse> calculateCharMove(MoveRpCharDto dto) {
```
Comment (Luktronic) [inline src/main/java/com/ardaslegends/presentation/api/MovementRestController.java:80]: same as above

**Review by Luktronic — DISMISSED** [review]
looks good, made some comments that should be addressed, but nothing regargind the functionality. Should be ready to merge 👍

File: src/main/java/com/ardaslegends/presentation/api/MovementRestController.java (hunk 3 above)
Comment (GroellerKarim) [reply src/main/java/com/ardaslegends/presentation/api/MovementRestController.java:67]: the move army dto will get translated as request parameters in this case, which is the way, I think, we prefer when talking about GET requests.

File: src/main/java/com/ardaslegends/presentation/api/MovementRestController.java (hunk 2 above)
Comment (GroellerKarim) [reply src/main/java/com/ardaslegends/presentation/api/MovementRestController.java]: done

File: src/main/java/com/ardaslegends/presentation/api/MovementRestController.java (hunk 1 above)
Comment (GroellerKarim) [reply src/main/java/com/ardaslegends/presentation/api/MovementRestController.java]: done

**Review by Luktronic — APPROVED** [review]
nnnbn
